### PR TITLE
adding automatic generated migration file

### PR DESCRIPTION
**Pull request by tiberius**
i had a problem when using the makemigrations django command, which failed at being able to write the appended migration file to the installed location in the system. this commit just adds what (my) django 1.8 makemigrations created when running with the appropriate permissions. i don't know whether or not this introduces any problems, it worked flawlessly on my installation setup, the error on makemigrations is gone and migrate applies cleanly.

### CODE REVIEW

**Comment by kylef** [comment]
Thanks @tiberius, I think this might be some Python 2 / 3 differences in the master migrations file. I'll have a dig into this.

**Comment by ajwilson08** [comment]
:+1: 
I needed this same migration when running Python 3.4/Django 1.8.3.

**Comment by felixxm** [comment]
Migration for ``request.method`` is unnecessary (see #79).

**Comment by felixxm** [comment]
Fixed in #79

**Pull request closed without merging**
